#' Gompertz function - an asymptotic growth commonly used to describe the growthrates in the marine environment.
#'
#' Author: Samantha Mislinski
#' This function determines the power generated by a given flow rate for a reservoir
#' @param N_0 initial population size
#' @param K carrying capacity of the species
#' @param r the growth rate
#' @param t the time
#' @return N_t Population size at time t
#'
# function definition
pop_size_func <- function(N_0, K, r, t){
  result <- K * exp(-exp(-r * t) * log(K/N_0))
  return(result)
} # End of pop_size_func

# K and r will be constant for each different species.
# N_0 and t can be changed. t can be made up data like a sequence of numbers.

